### ISSUE TITLE
Cookie Error

### ISSUE THREAD

**Issue by ItsMerkz** [Zday-X/INSTA-GEN#10]
AUTO GENERATING [ 10 ] ACCOUNTS! 

[Sit Back And Relax..This may take some time]
STARTED TO CREATE AN ACCOUNT
Using Email: guiltybass4@candassociates.comTraceback (most recent call last):
  File "insta-gen-gui.py", line 304, in <module>
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
  File "insta-gen-gui.py", line 287, in main
  File "insta-gen-gui.py", line 40, in _insta_gen
  File "requests\cookies.py", line 328, in __getitem__
  File "requests\cookies.py", line 399, in _find_no_duplicates
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by akaJuliaan** [comment]
you got ip banned => use a vpn or proxy
